Add more error handling

diff --git a/.github/actions/expo-update/action.yml b/.github/actions/expo-update/action.yml
--- a/.github/actions/expo-update/action.yml
+++ b/.github/actions/expo-update/action.yml
@@ -60,7 +60,10 @@ runs:
       id: perform-eas-update
       run: |
         platforms=("android" "ios")
-        eas_update_output=$(yarn nx run betterangels:eas-update --branch "${{ inputs.branch }}" --non-interactive --auto --json)
+        eas_update_output=$(yarn nx run "${{ inputs.project }}:eas-update" --branch "${{ inputs.branch }}" --non-interactive --auto --json) || {
+          echo "Error running the EAS update command"
+          exit 1
+        }
 
         for platform in "${platforms[@]}"; do
           update_info=$(echo "$eas_update_output" | jq -r ".[] | select(.platform == \"$platform\")")
