Try this

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -102,49 +102,49 @@ jobs:
         run: |
           docker compose up -d
 
-      - name: 🧹 Lint
-        run: |
-          docker compose run better-angels bash <<'EOF'
-          yarn nx affected -t lint
-          EOF
+      # - name: 🧹 Lint
+      #   run: |
+      #     docker compose run better-angels bash <<'EOF'
+      #     yarn nx affected -t lint
+      #     EOF
 
-      - name: 🕵️ Check for missing Django migrations
-        run: |
-          docker compose run better-angels bash <<'EOF'
-          yarn nx affected -t check-migrations
-          STATUS=$?
-          if [ $STATUS -ne 0 ]; then
-            echo "Error: Missing Django migrations! Make sure you have run 'python manage.py makemigrations <app_name>' locally and committed the changes."
-            exit 1
-          else
-            echo "Success: No missing Django migrations!"
-          fi
-          EOF
+      # - name: 🕵️ Check for missing Django migrations
+      #   run: |
+      #     docker compose run better-angels bash <<'EOF'
+      #     yarn nx affected -t check-migrations
+      #     STATUS=$?
+      #     if [ $STATUS -ne 0 ]; then
+      #       echo "Error: Missing Django migrations! Make sure you have run 'python manage.py makemigrations <app_name>' locally and committed the changes."
+      #       exit 1
+      #     else
+      #       echo "Success: No missing Django migrations!"
+      #     fi
+      #     EOF
 
-      - name: 📝 Make sure GraphQL Schema is up to date
-        # TODO: Upon graphql mismatch, a github action could commit the changes and push into the branch
-        run: |
-          docker compose run better-angels bash <<'EOF'
-          yarn nx affected -t validate-graphql-schema
-          STATUS=$?
-          if [ $STATUS -ne 0 ]; then
-            echo "Error: The GraphQL schemas do not match! Make sure you have run 'yarn nx affected -t generate-graphql-schema' locally and committed the changes."
-            exit 1
-          else
-            echo "Success: The GraphQL schemas match!"
-          fi
+      # - name: 📝 Make sure GraphQL Schema is up to date
+      #   # TODO: Upon graphql mismatch, a github action could commit the changes and push into the branch
+      #   run: |
+      #     docker compose run better-angels bash <<'EOF'
+      #     yarn nx affected -t validate-graphql-schema
+      #     STATUS=$?
+      #     if [ $STATUS -ne 0 ]; then
+      #       echo "Error: The GraphQL schemas do not match! Make sure you have run 'yarn nx affected -t generate-graphql-schema' locally and committed the changes."
+      #       exit 1
+      #     else
+      #       echo "Success: The GraphQL schemas match!"
+      #     fi
 
-          yarn nx affected -t generate-graphql-types
-          TYPE_GEN_STATUS=$?
-          git diff --exit-code '**/gql-types/*';
-          DIFF_STATUS=$?
-          if [ $TYPE_GEN_STATUS -ne 0 ] || [ $DIFF_STATUS -ne 0 ]; then
-            echo "Error: The GraphQL types do not match or generation failed! Make sure you have run 'yarn nx affected -t generate-graphql-types' locally and committed the changes."
-            exit 1
-          else
-            echo "Success: The GraphQL types match!"
-          fi
-          EOF
+      #     yarn nx affected -t generate-graphql-types
+      #     TYPE_GEN_STATUS=$?
+      #     git diff --exit-code '**/gql-types/*';
+      #     DIFF_STATUS=$?
+      #     if [ $TYPE_GEN_STATUS -ne 0 ] || [ $DIFF_STATUS -ne 0 ]; then
+      #       echo "Error: The GraphQL types do not match or generation failed! Make sure you have run 'yarn nx affected -t generate-graphql-types' locally and committed the changes."
+      #       exit 1
+      #     else
+      #       echo "Success: The GraphQL types match!"
+      #     fi
+      #     EOF
 
       - name: 🕵🏻‍♂️ GraphQL Inspector
         uses: kamilkisiela/graphql-inspector@master
