Give some nice output message

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -115,10 +115,17 @@ jobs:
           CI=1 yarn expo install --check
           EOF
 
-      - name: 🕵️ Check for missing migrations
+      - name: 🕵️ Check for missing Django migrations
         run: |
           docker-compose run better-angels bash <<'EOF'
           yarn nx affected -t check-migrations
+          STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "Error: Missing Django migrations! Make sure you have run 'python manage.py makemigrations <app_name>' locally and committed the changes."
+            exit 1
+          else
+            echo "Success: No missing Django migrations!"
+          fi
           EOF
 
       - name: 📝 Make sure GraphQL Schema is up to date
