feat(ci): add validate-graphql-types target for permission const diff check

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -129,14 +129,19 @@ jobs:
           fi
           EOF
 
-      - name: 📝 Make sure GraphQL Schema is up to date
-        # TODO: Upon graphql mismatch, a github action could commit the changes and push into the branch
+      - name: 📝 Make sure generated types are up to date
         run: |
           docker compose run better-angels bash <<'EOF'
           yarn nx affected -t validate-graphql-schema
           STATUS=$?
           if [ $STATUS -ne 0 ]; then
             echo "Error: The GraphQL schemas do not match! Make sure you have run 'yarn nx run-many -t generate-graphql-schema' locally and committed the changes."
+            exit 1
+          fi
+          yarn nx affected -t validate-graphql-types
+          STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "Error: The generated permission types do not match! Make sure you have run 'ynx-generate-types' locally and committed the changes."
             exit 1
           else
             echo "Success: The GraphQL schemas match!"
